# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_pl3YuCQmPzOeB8b2xA1ajKcrvasJ8LN
"""

# Japanese 50 Companies Quantitative Portfolio Analysis

!pip install yfinance pandas numpy matplotlib seaborn scipy openpyxl -q

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.optimize import minimize
import os


#  Create output folders


os.makedirs("charts", exist_ok=True)
os.makedirs("outputs", exist_ok=True)


#  Select 50 Japanese companies


companies = pd.DataFrame({
    "Company": [
        "Toyota Motor", "Sony Group", "SoftBank Group", "Mitsubishi UFJ Financial",
        "Nippon Telegraph and Telephone", "Keyence", "Tokyo Electron",
        "Sumitomo Mitsui Financial", "Shin-Etsu Chemical", "Hitachi",
        "Mitsubishi Corporation", "Nintendo", "Recruit Holdings", "Daiichi Sankyo",
        "KDDI", "Tokio Marine Holdings", "Honda Motor", "Itochu",
        "Mitsui & Co", "Mizuho Financial", "Canon", "Murata Manufacturing",
        "Denso", "Takeda Pharmaceutical", "Fast Retailing", "Daikin Industries",
        "Panasonic Holdings", "Nidec", "Mitsubishi Estate", "Bridgestone",
        "Japan Tobacco", "Chugai Pharmaceutical", "East Japan Railway",
        "Central Japan Railway", "Fujitsu", "NTT Data Group", "Japan Post Holdings",
        "SMC Corporation", "Disco Corporation", "MS&AD Insurance",
        "Nippon Steel", "ORIX", "Oriental Land", "Olympus", "Asahi Group",
        "Ajinomoto", "Otsuka Holdings", "LY Corporation", "Daiwa House",
        "INPEX"
    ],
    "Ticker": [
        "7203.T", "6758.T", "9984.T", "8306.T", "9432.T",
        "6861.T", "8035.T", "8316.T", "4063.T", "6501.T",
        "8058.T", "7974.T", "6098.T", "4568.T", "9433.T",
        "8766.T", "7267.T", "8001.T", "8031.T", "8411.T",
        "7751.T", "6981.T", "6902.T", "4502.T", "9983.T",
        "6367.T", "6752.T", "6594.T", "8802.T", "5108.T",
        "2914.T", "4519.T", "9020.T", "9022.T", "6702.T",
        "9613.T", "6178.T", "6273.T", "6146.T", "8725.T",
        "5401.T", "8591.T", "4661.T", "7733.T", "2502.T",
        "2802.T", "4578.T", "4689.T", "1925.T", "1605.T"
    ],
    "Sector": [
        "Automobile", "Technology", "Telecom/Investment", "Banking", "Telecom",
        "Technology", "Semiconductor", "Banking", "Chemicals", "Manufacturing",
        "Trading", "Gaming", "Services", "Healthcare", "Telecom",
        "Insurance", "Automobile", "Trading", "Trading", "Banking",
        "Technology", "Electronics", "Automobile", "Healthcare", "Retail",
        "Manufacturing", "Electronics", "Manufacturing", "Real Estate", "Automobile",
        "Consumer Goods", "Healthcare", "Transportation", "Transportation",
        "Technology", "Technology", "Financial Services", "Manufacturing",
        "Semiconductor", "Insurance", "Steel", "Financial Services",
        "Entertainment", "Healthcare", "Consumer Goods", "Consumer Goods",
        "Healthcare", "Internet Services", "Real Estate", "Energy"
    ],
    "Exchange": ["Tokyo Stock Exchange"] * 50
})

companies.to_csv("outputs/selected_50_japanese_companies.csv", index=False)
companies.head()

# Download historical prices


tickers = companies["Ticker"].tolist()

start_date = "2020-01-01"
end_date = "2026-06-15"

price_data = yf.download(
    tickers,
    start=start_date,
    end=end_date,
    auto_adjust=True
)["Close"]

price_data = price_data.dropna(axis=1, thresh=int(len(price_data) * 0.80))
price_data = price_data.ffill().dropna()

price_data.to_csv("outputs/historical_stock_prices.csv")

print("Final number of companies used:", len(price_data.columns))
price_data.head()

# Daily returns

returns = price_data.pct_change().dropna()
returns.to_csv("outputs/daily_returns.csv")

returns.head()

#  Benchmark data: Nikkei 225

benchmark = yf.download(
    "^N225",
    start=start_date,
    end=end_date,
    auto_adjust=True
)["Close"]

benchmark_returns = benchmark.pct_change().dropna()

common_dates = returns.index.intersection(benchmark_returns.index)

returns = returns.loc[common_dates]
benchmark_returns = benchmark_returns.loc[common_dates]

#Risk-return metrics

trading_days = 252
risk_free_rate = 0.01

metrics = pd.DataFrame(index=returns.columns)

metrics["Annual Return"] = returns.mean() * trading_days
metrics["Annual Volatility"] = returns.std() * np.sqrt(trading_days)
metrics["Sharpe Ratio"] = (metrics["Annual Return"] - risk_free_rate) / metrics["Annual Volatility"]


# Extract scalar value from benchmark_variance
benchmark_variance_scalar = benchmark_returns.var().item()

betas = []
for ticker in returns.columns:

    # Convert benchmark_returns to a 1D Series for compatibility with np.cov
    covariance = np.cov(returns[ticker], benchmark_returns.squeeze())[0][1]
    beta = covariance / benchmark_variance_scalar
    betas.append(beta)

metrics["Beta"] = betas

# Downside risk

downside_returns = returns.copy()
downside_returns[downside_returns > 0] = 0
metrics["Downside Risk"] = downside_returns.std() * np.sqrt(trading_days)

# Maximum drawdown

cumulative_prices = price_data[returns.columns]
drawdown = cumulative_prices / cumulative_prices.cummax() - 1
metrics["Maximum Drawdown"] = drawdown.min()

# Value at Risk

metrics["VaR 95"] = returns.quantile(0.05)
metrics["VaR 99"] = returns.quantile(0.01)

metrics = metrics.sort_values("Sharpe Ratio", ascending=False)

metrics.to_csv("outputs/risk_return_metrics.csv")
metrics.head(10)

# Price trend chart


normalized_prices = price_data[returns.columns] / price_data[returns.columns].iloc[0] * 100

plt.figure(figsize=(14, 7))
normalized_prices.iloc[:, :10].plot(figsize=(14, 7))
plt.title("Normalized Price Trends of First 10 Japanese Companies")
plt.xlabel("Date")
plt.ylabel("Normalized Price")
plt.grid(True)
plt.savefig("charts/price_trends.png", bbox_inches="tight")
plt.show()

#Return distribution


portfolio_daily_return = returns.mean(axis=1)

plt.figure(figsize=(10, 6))
plt.hist(portfolio_daily_return, bins=60)
plt.title("Return Distribution of Equal-Weighted Portfolio")
plt.xlabel("Daily Return")
plt.ylabel("Frequency")
plt.grid(True)
plt.savefig("charts/return_distribution.png", bbox_inches="tight")
plt.show()

# Volatility comparison


top_volatility = metrics.sort_values("Annual Volatility", ascending=False).head(15)

plt.figure(figsize=(12, 6))
plt.bar(top_volatility.index, top_volatility["Annual Volatility"])
plt.title("Top 15 Most Volatile Japanese Stocks")
plt.xlabel("Ticker")
plt.ylabel("Annual Volatility")
plt.xticks(rotation=45)
plt.grid(True)
plt.savefig("charts/volatility_comparison.png", bbox_inches="tight")
plt.show()

# Correlation matrix

correlation_matrix = returns.corr()
correlation_matrix.to_csv("outputs/correlation_matrix.csv")

plt.figure(figsize=(18, 14))
sns.heatmap(correlation_matrix, cmap="coolwarm", center=0)
plt.title("Correlation Heatmap of Japanese Stocks")
plt.savefig("charts/correlation_heatmap.png", bbox_inches="tight")
plt.show()

# Portfolio functions

mean_returns = returns.mean() * trading_days
cov_matrix = returns.cov() * trading_days
n = len(returns.columns)

def portfolio_performance(weights):
    portfolio_return = np.sum(mean_returns * weights)
    portfolio_volatility = np.sqrt(weights.T @ cov_matrix @ weights)
    sharpe_ratio = (portfolio_return - risk_free_rate) / portfolio_volatility
    return portfolio_return, portfolio_volatility, sharpe_ratio

def negative_sharpe(weights):
    return -portfolio_performance(weights)[2]

def portfolio_volatility(weights):
    return portfolio_performance(weights)[1]

constraints = {"type": "eq", "fun": lambda weights: np.sum(weights) - 1}
bounds = tuple((0, 0.10) for _ in range(n))
initial_weights = np.array([1 / n] * n)

# Equal-weighted portfolio

equal_weights = np.array([1 / n] * n)

eq_return, eq_volatility, eq_sharpe = portfolio_performance(equal_weights)

print("Equal-Weighted Portfolio")
print("Return:", eq_return)
print("Volatility:", eq_volatility)
print("Sharpe:", eq_sharpe)

# Minimum variance portfolio

min_var_result = minimize(
    portfolio_volatility,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

min_var_weights = min_var_result.x
min_return, min_volatility, min_sharpe = portfolio_performance(min_var_weights)

print("Minimum Variance Portfolio")
print("Return:", min_return)
print("Volatility:", min_volatility)
print("Sharpe:", min_sharpe)

# Maximum Sharpe ratio portfolio

max_sharpe_result = minimize(
    negative_sharpe,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

max_sharpe_weights = max_sharpe_result.x
max_return, max_volatility, max_sharpe = portfolio_performance(max_sharpe_weights)

print("Maximum Sharpe Portfolio")
print("Return:", max_return)
print("Volatility:", max_volatility)
print("Sharpe:", max_sharpe)

# Portfolio comparison

portfolio_results = pd.DataFrame({
    "Portfolio": [
        "Equal Weighted",
        "Minimum Variance",
        "Maximum Sharpe"
    ],
    "Annual Return": [
        eq_return,
        min_return,
        max_return
    ],
    "Annual Volatility": [
        eq_volatility,
        min_volatility,
        max_volatility
    ],
    "Sharpe Ratio": [
        eq_sharpe,
        min_sharpe,
        max_sharpe
    ]
})

portfolio_results.to_csv("outputs/portfolio_results.csv", index=False)
portfolio_results

# Portfolio comparison chart

portfolio_results.set_index("Portfolio")[["Annual Return", "Annual Volatility", "Sharpe Ratio"]].plot(
    kind="bar",
    figsize=(12, 6)
)

plt.title("Portfolio Performance Comparison")
plt.ylabel("Metric Value")
plt.xticks(rotation=0)
plt.grid(True)
plt.savefig("charts/portfolio_comparison.png", bbox_inches="tight")
plt.show()

# Efficient frontier


num_portfolios = 10000

frontier_results = np.zeros((3, num_portfolios))

for i in range(num_portfolios):
    weights = np.random.random(n)
    weights = weights / np.sum(weights)

    ret, vol, sharpe = portfolio_performance(weights)

    frontier_results[0, i] = ret
    frontier_results[1, i] = vol
    frontier_results[2, i] = sharpe

plt.figure(figsize=(12, 7))
plt.scatter(
    frontier_results[1, :],
    frontier_results[0, :],
    c=frontier_results[2, :],
    cmap="viridis",
    s=8
)

plt.colorbar(label="Sharpe Ratio")
plt.scatter(max_volatility, max_return, marker="*", s=300, label="Maximum Sharpe Portfolio")
plt.scatter(min_volatility, min_return, marker="*", s=300, label="Minimum Variance Portfolio")
plt.xlabel("Annual Volatility")
plt.ylabel("Annual Return")
plt.title("Efficient Frontier")
plt.legend()
plt.grid(True)
plt.savefig("charts/efficient_frontier.png", bbox_inches="tight")
plt.show()

# Portfolio allocation tables


allocation_df = pd.DataFrame({
    "Ticker": returns.columns,
    "Company": companies.set_index("Ticker").loc[returns.columns]["Company"].values,
    "Sector": companies.set_index("Ticker").loc[returns.columns]["Sector"].values,
    "Equal Weight": equal_weights,
    "Minimum Variance Weight": min_var_weights,
    "Maximum Sharpe Weight": max_sharpe_weights
})

allocation_df.to_csv("outputs/portfolio_allocation.csv", index=False)
allocation_df.head()

# Maximum Sharpe allocation chart


max_alloc = allocation_df[allocation_df["Maximum Sharpe Weight"] > 0.001]
max_alloc = max_alloc.sort_values("Maximum Sharpe Weight", ascending=False)

plt.figure(figsize=(12, 6))
plt.bar(max_alloc["Ticker"], max_alloc["Maximum Sharpe Weight"])
plt.title("Maximum Sharpe Portfolio Allocation")
plt.xlabel("Ticker")
plt.ylabel("Weight")
plt.xticks(rotation=45)
plt.grid(True)
plt.savefig("charts/max_sharpe_allocation.png", bbox_inches="tight")
plt.show()

# Sector-wise exposure

sector_exposure = allocation_df.groupby("Sector")[
    ["Equal Weight", "Minimum Variance Weight", "Maximum Sharpe Weight"]
].sum()

sector_exposure.to_csv("outputs/sector_exposure.csv")

sector_exposure.plot(kind="bar", figsize=(14, 7))
plt.title("Sector-Wise Portfolio Exposure")
plt.xlabel("Sector")
plt.ylabel("Portfolio Weight")
plt.xticks(rotation=45)
plt.grid(True)
plt.savefig("charts/sector_exposure.png", bbox_inches="tight")
plt.show()

# Identify key companies


high_return = metrics.sort_values("Annual Return", ascending=False).head(10)
high_risk = metrics.sort_values("Annual Volatility", ascending=False).head(10)
low_volatility = metrics.sort_values("Annual Volatility", ascending=True).head(10)
stable_performance = metrics.sort_values("Sharpe Ratio", ascending=False).head(10)

avg_corr = correlation_matrix.mean().sort_values()
diversification_value = avg_corr.head(10)

high_return.to_csv("outputs/high_return_companies.csv")
high_risk.to_csv("outputs/high_risk_companies.csv")
low_volatility.to_csv("outputs/low_volatility_companies.csv")
stable_performance.to_csv("outputs/stable_performance_companies.csv")
diversification_value.to_csv("outputs/strong_diversification_value.csv")

print("High Return Companies")
display(high_return)

print("Low Volatility Companies")
display(low_volatility)

print("Stable Performance Companies")
display(stable_performance)

print("Strong Diversification Value")
display(diversification_value)

# Generate simple final report text


report_text = f"""
Quantitative Analysis of 50 Publicly Listed Japanese Companies

1. Objective
The objective of this project is to evaluate the risk, return, correlation,
diversification potential, and portfolio optimization performance of selected
Japanese publicly listed companies.

2. Dataset
The analysis uses historical adjusted closing prices from Yahoo Finance.
The selected companies are listed on the Tokyo Stock Exchange and represent
sectors such as automobile, banking, technology, healthcare, manufacturing,
consumer goods, energy, insurance, telecom, and financial services.

3. Methodology
Daily returns were calculated from historical stock prices. Annualized return,
annualized volatility, Sharpe ratio, beta, downside risk, maximum drawdown,
and Value at Risk were calculated for each company.

4. Portfolio Models
Three portfolios were constructed:
- Equal-weighted portfolio
- Minimum variance portfolio
- Maximum Sharpe ratio portfolio

5. Portfolio Results
Equal Weighted Portfolio:
Annual Return: {eq_return:.4f}
Annual Volatility: {eq_volatility:.4f}
Sharpe Ratio: {eq_sharpe:.4f}

Minimum Variance Portfolio:
Annual Return: {min_return:.4f}
Annual Volatility: {min_volatility:.4f}
Sharpe Ratio: {min_sharpe:.4f}

Maximum Sharpe Portfolio:
Annual Return: {max_return:.4f}
Annual Volatility: {max_volatility:.4f}
Sharpe Ratio: {max_sharpe:.4f}

6. Interpretation
The equal-weighted portfolio provides simple diversification across all
selected companies. The minimum variance portfolio focuses on reducing total
risk, while the maximum Sharpe portfolio aims to generate the highest
risk-adjusted return.

7. Key Findings
The analysis identifies companies with high return potential, high risk,
low volatility, stable performance, and strong diversification value.
The correlation matrix helps identify whether selected companies move together
or provide diversification benefits.

8. Limitations
This analysis is based on historical stock price data. Future performance may
differ due to macroeconomic conditions, interest rates, currency movement,
company fundamentals, and market shocks.

9. Conclusion
The project shows that quantitative portfolio analysis can help compare
individual stocks and portfolio strategies. Optimization improves the
understanding of risk-return trade-offs and sector concentration.
"""

with open("outputs/final_report.txt", "w") as f:
    f.write(report_text)

print(report_text)

# Zip all outputs for download

!zip -r japan_quant_project_outputs.zip outputs charts

from google.colab import files
files.download("japan_quant_project_outputs.zip")